version: "3.9"
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - ./backend:/backend
    depends_on:
      - frontend

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
