FROM python:3.9

WORKDIR /backend

COPY requirements.txt /backend

RUN pip install gunicorn && pip install -r requirements.txt

COPY . .

ENV FLASK_ENV production

EXPOSE 5000

CMD ["gunicorn", "-b", ":5000", "App:app"]